// flow-typed signature: bf20864aa2158de02f4546d7971a9526
// flow-typed version: <<STUB>>/fake-indexeddb_v^1.0.12/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fake-indexeddb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fake-indexeddb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fake-indexeddb/dist/fakeIndexedDB' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/exports' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/addDomStringListMethods' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/cmp' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/Database' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/errors/AbortError' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/errors/ConstraintError' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/errors/DataCloneError' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/errors/DataError' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/errors/InvalidAccessError' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/errors/InvalidStateError' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/errors/NotFoundError' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/errors/ReadOnlyError' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/errors/TransactionInactiveError' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/errors/VersionError' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/Event' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/EventTarget' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/extractKey' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/FDBCursor' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/FDBCursorWithValue' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/FDBDatabase' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/FDBFactory' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/FDBIndex' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/FDBKeyRange' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/FDBObjectStore' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/FDBOpenDBRequest' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/FDBRequest' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/FDBTransaction' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/FDBVersionChangeEvent' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/Index' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/KeyGenerator' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/ObjectStore' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/structuredClone' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/validateKey' {
  declare module.exports: any;
}

declare module 'fake-indexeddb/lib/validateKeyPath' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fake-indexeddb/dist/fakeIndexedDB.js' {
  declare module.exports: $Exports<'fake-indexeddb/dist/fakeIndexedDB'>;
}
declare module 'fake-indexeddb/exports.js' {
  declare module.exports: $Exports<'fake-indexeddb/exports'>;
}
declare module 'fake-indexeddb/index' {
  declare module.exports: $Exports<'fake-indexeddb'>;
}
declare module 'fake-indexeddb/index.js' {
  declare module.exports: $Exports<'fake-indexeddb'>;
}
declare module 'fake-indexeddb/lib/addDomStringListMethods.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/addDomStringListMethods'>;
}
declare module 'fake-indexeddb/lib/cmp.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/cmp'>;
}
declare module 'fake-indexeddb/lib/Database.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/Database'>;
}
declare module 'fake-indexeddb/lib/errors/AbortError.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/errors/AbortError'>;
}
declare module 'fake-indexeddb/lib/errors/ConstraintError.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/errors/ConstraintError'>;
}
declare module 'fake-indexeddb/lib/errors/DataCloneError.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/errors/DataCloneError'>;
}
declare module 'fake-indexeddb/lib/errors/DataError.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/errors/DataError'>;
}
declare module 'fake-indexeddb/lib/errors/InvalidAccessError.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/errors/InvalidAccessError'>;
}
declare module 'fake-indexeddb/lib/errors/InvalidStateError.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/errors/InvalidStateError'>;
}
declare module 'fake-indexeddb/lib/errors/NotFoundError.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/errors/NotFoundError'>;
}
declare module 'fake-indexeddb/lib/errors/ReadOnlyError.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/errors/ReadOnlyError'>;
}
declare module 'fake-indexeddb/lib/errors/TransactionInactiveError.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/errors/TransactionInactiveError'>;
}
declare module 'fake-indexeddb/lib/errors/VersionError.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/errors/VersionError'>;
}
declare module 'fake-indexeddb/lib/Event.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/Event'>;
}
declare module 'fake-indexeddb/lib/EventTarget.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/EventTarget'>;
}
declare module 'fake-indexeddb/lib/extractKey.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/extractKey'>;
}
declare module 'fake-indexeddb/lib/FDBCursor.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/FDBCursor'>;
}
declare module 'fake-indexeddb/lib/FDBCursorWithValue.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/FDBCursorWithValue'>;
}
declare module 'fake-indexeddb/lib/FDBDatabase.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/FDBDatabase'>;
}
declare module 'fake-indexeddb/lib/FDBFactory.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/FDBFactory'>;
}
declare module 'fake-indexeddb/lib/FDBIndex.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/FDBIndex'>;
}
declare module 'fake-indexeddb/lib/FDBKeyRange.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/FDBKeyRange'>;
}
declare module 'fake-indexeddb/lib/FDBObjectStore.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/FDBObjectStore'>;
}
declare module 'fake-indexeddb/lib/FDBOpenDBRequest.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/FDBOpenDBRequest'>;
}
declare module 'fake-indexeddb/lib/FDBRequest.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/FDBRequest'>;
}
declare module 'fake-indexeddb/lib/FDBTransaction.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/FDBTransaction'>;
}
declare module 'fake-indexeddb/lib/FDBVersionChangeEvent.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/FDBVersionChangeEvent'>;
}
declare module 'fake-indexeddb/lib/Index.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/Index'>;
}
declare module 'fake-indexeddb/lib/KeyGenerator.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/KeyGenerator'>;
}
declare module 'fake-indexeddb/lib/ObjectStore.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/ObjectStore'>;
}
declare module 'fake-indexeddb/lib/structuredClone.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/structuredClone'>;
}
declare module 'fake-indexeddb/lib/validateKey.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/validateKey'>;
}
declare module 'fake-indexeddb/lib/validateKeyPath.js' {
  declare module.exports: $Exports<'fake-indexeddb/lib/validateKeyPath'>;
}
